name: 'Repo Dispatch -- feat. Yaml ClientPayload'
description: 'Yet another repo dispatch. But with yaml as clientPayload input'
author: 'maxisam'
branding:
  icon: send
  color: purple
inputs:
  authToken:
    description: 'Use your own token if you need to trigger other workflows'
    required: true
  owner:
    description: 'Repostory owner, defaults to context github.repository_owner if omited'
    default: ${{ github.repository_owner }}
    required: false
  repository:
    description: 'Repository, default to context github.repository if omited'
    default: ${{ github.repository }}
    required: false
  eventType:
    description: 'eventType of repo dispatch'
    default: 'repo-dispatch'
    required: false
  clientPayload:
    description: 'clientPayload in yaml format'
    default: ''
    required: false
  targetWorkflowId:
    description: 'workflow id/ yaml file to trigger, with this input, it can trace the triggered workflow'
    default: ''
    required: false
  triggeredWorkflowTitleKeyword:
    description: 'keyword contained in triggered workflow title, with this input, it can trace the triggered workflow'
    default: ''
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
