name: '🌞 CI'

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - dist/**
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - dist/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref}}
          fetch-depth: 0

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install

      - run: yarn all

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            echo "diff=true" >> $GITHUB_OUTPUT
            echo "::notice title=Change detected::Detected uncommitted changes after build"
          fi

      - name: commit build
        if: ${{ steps.diff.outputs.diff }}
        run: |
          git config --local user.email "maxisam@gmail.com"
          git config --local user.name "maxisam"
          git add dist/
          git commit -m "chore: build, dist updated"
          git push origin ${{ github.head_ref || github.ref_name }}

  repo-dispatch:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          authToken: ${{secrets.GH_AUTH_TOKEN}}
          eventType: 'test-repo-dispatch'
          targetWorkflowId: repo-dispatch.yml
          triggeredWorkflowTitleKeyword: 💥Title
          clientPayload: |
            message: |
              🚀 Works
              - test 1
              - test 2
            subject: 💥Title
