name: 💥REPO DISPATCH
run-name: '${{ github.event.client_payload.subject }}'

on:
  repository_dispatch:
    types: [test-repo-dispatch]

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Test Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          BODY="${{ github.event.client_payload.message }}"
          ISSUE=$(gh issue create \
            --body "${BODY}" \
            --label ci-test \
            --title "${{ github.event.client_payload.subject }}")
          gh issue close $ISSUE
